
title: BHAVANA CHINTHAMANI
theme: jekyll-theme-minimal

logo: /assets/img/ProfilePic.png

description: >
  Data Scientist | AI & Machine Learning Enthusiast  
  Passionate about building intelligent and data-driven solutions.

show_downloads: false
