title: BHAVANA CHINTHAMANI
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # You can choose: air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise

author:
  name: "Bhavana Chinthamani"
  avatar: "/assets/img/ProfilePic.png"
  location: "Bangalore"

show_excerpts: true